// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type { BaseClientOptions } from "@xata.io/client";
import { apiKey } from "better-auth/plugins";

export type DatabaseSchema = {};

const DatabaseClient = buildClient();

const defaultOptions = {
	databaseURL:
		"https://Chenyang-Zhao-s-workspace-4ber42.ap-southeast-2.xata.sh/db/snapcast",
	apiKey: process.env.XATA_API_KEY,
	branch: "main",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
	constructor(options?: BaseClientOptions) {
		super({ ...defaultOptions, ...options });
	}
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
	if (instance) return instance;

	instance = new XataClient();
	return instance;
};
